### ISSUE TITLE
Enhancement of the documentation for a from scratch install

### ISSUE THREAD

**Issue by pamiel** [ThalesGroup/gokube#11]
Documentation is missing 3 steps when running an installation _from scratch_:
- If behind a proxy, it is required to set the HTTP_PROXY and HTTPS_PROXY envvars in order to run the `gokube init` command. Otherwise, no way to upload the packages from Internet
- When running `gokube init`, an error message saying that `minikube.exe` cannot be found is displayed. Indeed, `gokube init` has not detected that none of the dependencies (including minikube) were there => it is required to run `gokube init -u` instead to upload the dependencies for the first time. Would be good to update the documentation or to manage this use case in the `gokube init` implementation
- At the end of the `gokube init -u` command, the `kubectl get pod --all-namespaces` command cannot be run immediately: it is required to start minikube first, by running the `minikube start` command. And if being behind a proxy, the HTTP_PROXY, HTTPS_PROXY and NO_PROXY envvars shall be set (make a reference to https://minikube.sigs.k8s.io/docs/reference/networking/proxy/) before running `minikube start`.

**Comment by cvila84** [comment]
- Documentation updated to indicate environment variables for proxy are taken into account.
- Upgrade is forced when gokube is used for the first time or if gokube new version has been installed.
- When init command is successfully run, K8S is immediately available
