### ISSUE TITLE
Misleading error message when `gokube start` fails to verify ssh connectivity

### ISSUE THREAD

**Issue by Honza-cz** [ThalesGroup/gokube#19]
When `gokube start` fails due to ssh connectivity, one of the proposed solution in error message is 

>  - Use --force to override this connectivity check 

This option is unsupported:
`
gokube start --force
WARNING: Cannot find gokube latest release, please check your connection
Error: unknown flag: --force
`

[gokube-force.txt](https://github.com/ThalesGroup/gokube/files/4454578/gokube-force.txt)

Possible workaround is to call twice 

> gokube start

Better solution is to let define a timeout how long the gokube should wait before giving up ssh connectivity check and returning an error

**Comment by cvila84** [comment]
Thank you to post an issue here !

This message is printed by minikube start command, which is launched by gokube init command. gokube will not call minikube with this flag as enforcing SSH connectivity check will lead to other errors later (helm installation) and the objective of gokube is to generate automatically a VM up and ready to serve without need of hacking it after. If there are errors, it is better to try to understand them (environment, network or virtualbox issues ?)

There is actually a misleading thing with this flag as gokube init command (not start) also has its own `--force` flag (you can see it in typing `gokube init --help`) that does something else (remove a warning message). Maybe an improvement could be to rename this flag to avoid confusion.

**Comment by jroucheton** [comment]
+1 for renaming.

**Comment by cvila84** [comment]
gokube `--force` flag for init and stop commands has been replaced by `--quiet`
