### ISSUE TITLE
gokube reset is not warning like gokube init is

### ISSUE THREAD

**Issue by Mvek** [ThalesGroup/gokube#23]
When running gokube init, it warns user and gives few seconds to cancel it.
When running gokube reset, it is not the case.

It is not high priority or importance, but would be nice to have the behaviour same to avoid losing working env by accidental call from command line history.

**Comment by cvila84** [comment]
the warning you have for init command is

```
WARNING: Your Virtualbox GUI shall not be open and no other VM shall be currently running
Press <CTRL+C> within the next 10s it you need to check this or press <ENTER> now to continue...

```

for reset command, there is nothing to check to be able to run successfully the command, so there is no need to warn the user
