### ISSUE TITLE
gokube warns about a new version, but it is a beta version

### ISSUE THREAD

**Issue by Mvek** [ThalesGroup/gokube#24]
gokube 1.22.1 is WARNING that current version is outdated and we should download newest one from https://github.com/ThalesGroup/gokube/releases/tag/v1.23.2-beta.1

But 1.22.1 is the latest version and there is only beta version.

Anyway a lot of people are using beta version now due to this warning as I have learned today.

**Comment by cvila84** [comment]
the warning shall be removed if newer versions contain pre-release information (from semver specification)

**Comment by cvila84** [comment]
this problem happened because some gokube beta versions were released without pre-release option set (github option). starting from now, all non-final gokube versions (beta) will have their releases in github marked with pre-release option, so they won't trigger such warning anymore.

we can close
